create table if not exists public.community_members (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  telegram_user_id bigint not null,
  telegram_username text,
  display_name text,
  player_tag text,
  player_name text,
  club_name text not null default 'TITANI ABUSIVI' check (club_name in ('TITANI ABUSIVI','TAMARRI ABUSIVI','TORNADI ABUSIVI','TALENTI ABUSIVI')),
  role text default 'member',
  last_seen_at timestamptz default now(),
  last_warning_at timestamptz,
  vacation_until timestamptz,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (chat_id, telegram_user_id)
);

alter table public.community_members add column if not exists ranked_current text;
alter table public.community_members add column if not exists ranked_current_elo integer;
alter table public.community_members add column if not exists ranked_peak text;
alter table public.community_members add column if not exists ranked_season_peak text;
alter table public.community_members add column if not exists ranked_season_peak_elo integer;
alter table public.community_members add column if not exists ranked_career_peak text;
alter table public.community_members add column if not exists ranked_career_peak_elo integer;
alter table public.community_members add column if not exists player_last_updated_at timestamptz;

create table if not exists public.trophy_history (
  id bigint generated by default as identity primary key,
  player_tag text not null,
  player_name text,
  trophies integer not null,
  recorded_at timestamptz not null default now()
);
create index if not exists trophy_history_tag_time_idx
  on public.trophy_history (player_tag, recorded_at desc);

create table if not exists public.player_tracking_state (
  player_tag text primary key,
  player_name text,
  trophies integer,
  ranked_current text,
  ranked_current_elo integer,
  ranked_season_peak text,
  ranked_season_peak_elo integer,
  ranked_career_peak text,
  ranked_career_peak_elo integer,
  last_checked_at timestamptz not null default now()
);

create table if not exists public.ranked_history (
  id bigint generated by default as identity primary key,
  player_tag text not null,
  player_name text,
  ranked_current text,
  ranked_current_elo integer,
  ranked_season_peak text,
  ranked_season_peak_elo integer,
  ranked_career_peak text,
  ranked_career_peak_elo integer,
  recorded_at timestamptz not null default now()
);
create index if not exists ranked_history_tag_time_idx
  on public.ranked_history (player_tag, recorded_at desc);

create index if not exists community_members_chat_idx
  on public.community_members (chat_id, is_active);
create index if not exists community_members_player_tag_idx
  on public.community_members (player_tag);
create index if not exists community_members_club_idx
  on public.community_members (club_name, is_active);

create table if not exists public.community_settings (
  chat_id bigint primary key,
  inactivity_warn_days integer not null default 5,
  inactivity_kick_days integer not null default 10,
  auto_kick boolean not null default false,
  daily_report_enabled boolean not null default false,
  weekly_report_enabled boolean not null default false,
  report_hour integer not null default 9,
  last_daily_report_date text,
  last_weekly_report_key text,
  updated_at timestamptz not null default now()
);

create table if not exists public.community_events (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  name text not null,
  event_at timestamptz not null,
  mandatory boolean not null default false,
  status text not null default 'open',
  created_by bigint not null,
  reminder_sent boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists community_events_chat_time_idx
  on public.community_events (chat_id, event_at);

create table if not exists public.community_event_participants (
  event_id bigint not null references public.community_events(id) on delete cascade,
  telegram_user_id bigint not null,
  status text not null default 'confirmed',
  updated_at timestamptz not null default now(),
  primary key (event_id, telegram_user_id)
);

create table if not exists public.community_recruitments (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  telegram_user_id bigint not null,
  telegram_username text,
  display_name text,
  player_tag text not null,
  ranked text,
  notes text,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create index if not exists community_recruitments_chat_status_idx
  on public.community_recruitments (chat_id, status, created_at desc);

alter table public.community_members enable row level security;
alter table public.community_settings enable row level security;
alter table public.community_events enable row level security;
alter table public.community_event_participants enable row level security;
alter table public.community_recruitments enable row level security;
alter table public.trophy_history enable row level security;
alter table public.player_tracking_state enable row level security;
alter table public.ranked_history enable row level security;

-- Dal 2026 i nuovi progetti Supabase non espongono automaticamente le nuove
-- tabelle alla Data API. Il bot usa esclusivamente la service role sul server.
grant select, insert, update, delete on table public.trophy_history to service_role;
grant select, insert, update, delete on table public.player_tracking_state to service_role;
grant select, insert, update, delete on table public.ranked_history to service_role;
grant usage, select on all sequences in schema public to service_role;
